services:
  logic:
    build: logic
    depends_on:
    - db

  api:
    build: api
    ports:
    - 8080:80
    depends_on:
    - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:
