services:
  # logic:
  #   build: logic

  api:
    build: api
    ports:
    - 8080:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
